<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-ITSGITUD" failures="1" tests="6" name="WebServices-Test" time="11.899" errors="0" timestamp="2023-10-05T10:21:30 IST">
  <testcase classname="calc.testCases.CalcDemoTC.CalcTest" name="VerifyCalcOperations" time="0.36"/>
  <testcase classname="calc.testCases.CalcDemoTC.CalcTest" name="VerifyCalcOperations" time="0.327"/>
  <testcase classname="calc.testCases.CalcDemoTC.CalcTest" name="VerifyCalcOperations" time="0.289"/>
  <testcase classname="calc.testCases.CalcDemoTC.CalcTest" name="VerifyCalcOperations" time="0.295"/>
  <testcase classname="calc.testCases.CalcDemoTC.CalcTest" name="VerifyCalcOperations" time="0.334">
    <failure type="java.lang.AssertionError" message=" Actual value is : 2.0 Expected value is : 3.0 did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError:  Actual value is : 2.0 Expected value is : 3.0 did not expect to find [true] but found [false]
at calc.utility.reports.Reporter.logFail(Reporter.java:153)
at calc.utility.reports.Reporter.logIntoReport(Reporter.java:128)
at calc.wspages.calcDemo.WebCalcLoad.validateResult(WebCalcLoad.java:211)
at calc.testCases.CalcDemoTC.CalcTest.VerifyCalcOperations(CalcTest.java:53)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- VerifyCalcOperations -->
  <testcase classname="calc.testCases.CalcDemoTC.CalcTest" name="VerifyCalcOperations" time="0.324"/>
</testsuite> <!-- WebServices-Test -->
