<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-ITSGITUD" failures="1" tests="4" name="calc.wstestCases.wsCarbonCredits.CalcTest" time="5.851" errors="0" timestamp="2023-10-05T01:00:47 IST" skipped="0">
  <testcase classname="calc.wstestCases.wsCarbonCredits.CalcTest" name="VerifyCalcOperations" time="1.678"/>
  <testcase classname="calc.wstestCases.wsCarbonCredits.CalcTest" name="VerifyCalcOperations" time="1.550"/>
  <testcase classname="calc.wstestCases.wsCarbonCredits.CalcTest" name="VerifyCalcOperations" time="1.259">
    <failure message=" Expected value is : 2.0 Actual value is : 3.0 did not expect to find [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError:  Expected value is : 2.0 Actual value is : 3.0 did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at calc.utility.reports.Reporter.logFail(Reporter.java:153)
at calc.utility.reports.Reporter.logIntoReport(Reporter.java:128)
at calc.wspages.carbonCredit.WebCalcLoad.validateResult(WebCalcLoad.java:202)
at calc.wstestCases.wsCarbonCredits.CalcTest.VerifyCalcOperations(CalcTest.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifyCalcOperations -->
  <testcase classname="calc.wstestCases.wsCarbonCredits.CalcTest" name="VerifyCalcOperations" time="1.364"/>
</testsuite> <!-- calc.wstestCases.wsCarbonCredits.CalcTest -->
